repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        name: ruff check (with fix)
        args: ["--fix"]
      - id: ruff-format
        name: ruff format

  - repo: local
    hooks:
      - id: ty
        name: ty static analysis
        entry: ty check
        language: system
        types: [python]
        pass_filenames: true

      - id: tests
        name: run tests
        entry: python -m unittest discover -v tests
        language: python
        types: [python]
        stages: [commit]
